linters:
  enable:
    - lll
    - gofumpt
    - goconst
    - gosimple
    - misspell
    - stylecheck
    # style linters start
    - asciicheck
    - whitespace
    - unconvert
    - predeclared
    - importas
    - reassign
    - cyclop
    - nestif
    - revive
    # style linters end
  disable:
    - forcetypeassert
    # deprecated linters start
    - maligned
    - contextcheck
    # deprecated linters end
    - goimports
    - musttag
    - depguard
    - gosmopolitan
    - perfsprint
  presets:
    - import
    - bugs
    - unused
    - performance

# all available settings of specific linters
linters-settings:
  nestif:
    # Minimal complexity of if statements to report.
    # Default: 5
    min-complexity: 4
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 20
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 10
    # Should ignore tests.
    # Default: false
    skip-tests: true
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 4
  gci:
    # Checks that no inline Comments are present.
    # Default: false
    # no-inline-comments: true
    # Checks that no prefix Comments(comment lines above an import) are present.
    # Default: false
    # no-prefix-comments: true
    # Section configuration to compare against.
    # Section names are case-insensitive and may contain parameters in ().
    # Default: ["standard", "default"]
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/go-demo/) # Groups all imports with the specified Prefix.
    # Separators that should be present between sections.
    # Default: ["newLine"]
    # section-separators:
    #   - newLine
  gofumpt:
    # Choose whether or not to use the extra rules that are disabled
    # by default
    extra-rules: false
    module-path: github.com/go-demo/
  revive:
    severity: warning
    rules:
      - name: max-control-nesting
        severity: warning
        disabled: false
        exclude: [""]
        arguments: [4]

issues:
  exclude-dirs:
    - ^gen/
    - /opt/opt/homebrew/Cellar/go/*
  exclude:
    - "^SA1019: problem\\..*"
